## Notebook for Manual Analysis of Generated Tables

In [ ]:
import pandas as pd
import numpy as np
import json
from utils.utils import *
import pprint
from eval.eval import *
from post_processing.post_processing import *
from utils.table_utils import *
from model_inference.gpt import *
from model_inference.llama import *
from model_inference.gemini import *
eval_rows = 725
model_output_file = "./model_outputs/llama_baseline_2610_117AM/tables_gpt_trial.json"
statements ="./model_outputs/llama_baseline_2610_117AM/ai_response.json"
headers = "./model_outputs/llama_baseline_2610_117AM/headers.json"
gold_table_file = "../data/rotowire/test.text"

In [ ]:
df = pd.read_json('../data/rotowire_og/test.json')

In [44]:
df.columns

Index(['home_name', 'box_score', 'home_city', 'vis_name', 'summary',
       'vis_line', 'vis_city', 'day', 'home_line'],
      dtype='object')

In [47]:
# print(' '.join(df['summary'][0]))
df['box_score'][0]

{'TO': {'24': 'N/A',
  '25': 'N/A',
  '20': '4',
  '21': '0',
  '22': '2',
  '23': 'N/A',
  '1': '4',
  '0': '2',
  '3': '2',
  '2': '4',
  '5': '1',
  '4': '2',
  '7': '0',
  '6': '2',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '2',
  '12': 'N/A',
  '15': '1',
  '14': '2',
  '17': '3',
  '16': '1',
  '19': '3',
  '18': '0'},
 'FIRST_NAME': {'24': 'John',
  '25': 'Mike',
  '20': 'Dennis',
  '21': 'Shelvin',
  '22': 'Mike',
  '23': 'Elton',
  '1': 'Channing',
  '0': 'Tobias',
  '3': 'Victor',
  '2': 'Nikola',
  '5': 'Dewayne',
  '4': 'Elfrid',
  '7': 'Andrew',
  '6': 'Willie',
  '9': 'Luke',
  '8': 'Kyle',
  '11': 'Ben',
  '10': 'Maurice',
  '13': 'DeMarre',
  '12': 'Devyn',
  '15': 'Al',
  '14': 'Paul',
  '17': 'Jeff',
  '16': 'Kyle',
  '19': 'Kent',
  '18': 'Pero'},
 'MIN': {'24': 'N/A',
  '25': 'N/A',
  '20': '14',
  '21': '7',
  '22': '17',
  '23': 'N/A',
  '1': '24',
  '0': '37',
  '3': '35',
  '2': '37',
  '5': '11',
  '4': '26',
  '7': '10',
  '6': '28',
  '9': '13',
  '8': '5',
  '11': 'N/A',
  '10': '14',
  '13': '31',
  '12': 'N/A',
  '15': '31',
  '14': '35',
  '17': '33',
  '16': '35',
  '19': '24',
  '18': '14'},
 'REB': {'24': 'N/A',
  '25': 'N/A',
  '20': '2',
  '21': '0',
  '22': '6',
  '23': 'N/A',
  '1': '3',
  '0': '4',
  '3': '3',
  '2': '15',
  '5': '3',
  '4': '1',
  '7': '4',
  '6': '2',
  '9': '1',
  '8': '1',
  '11': 'N/A',
  '10': '3',
  '13': '8',
  '12': 'N/A',
  '15': '13',
  '14': '4',
  '17': '0',
  '16': '3',
  '19': '1',
  '18': '5'},
 'FG3A': {'24': 'N/A',
  '25': 'N/A',
  '20': '2',
  '21': '2',
  '22': '2',
  '23': 'N/A',
  '1': '8',
  '0': '4',
  '3': '5',
  '2': '0',
  '5': '0',
  '4': '0',
  '7': '2',
  '6': '3',
  '9': '2',
  '8': '0',
  '11': 'N/A',
  '10': '2',
  '13': '6',
  '12': 'N/A',
  '15': '0',
  '14': '7',
  '17': '4',
  '16': '5',
  '19': '2',
  '18': '1'},
 'PLAYER_NAME': {'24': 'John Jenkins',
  '25': 'Mike Muscala',
  '20': 'Dennis Schroder',
  '21': 'Shelvin Mack',
  '22': 'Mike Scott',
  '23': 'Elton Brand',
  '1': 'Channing Frye',
  '0': 'Tobias Harris',
  '3': 'Victor Oladipo',
  '2': 'Nikola Vucevic',
  '5': 'Dewayne Dedmon',
  '4': 'Elfrid Payton',
  '7': 'Andrew Nicholson',
  '6': 'Willie Green',
  '9': 'Luke Ridnour',
  '8': "Kyle O'Quinn",
  '11': 'Ben Gordon',
  '10': 'Maurice Harkless',
  '13': 'DeMarre Carroll',
  '12': 'Devyn Marble',
  '15': 'Al Horford',
  '14': 'Paul Millsap',
  '17': 'Jeff Teague',
  '16': 'Kyle Korver',
  '19': 'Kent Bazemore',
  '18': 'Pero Antic'},
 'AST': {'24': 'N/A',
  '25': 'N/A',
  '20': '3',
  '21': '1',
  '22': '1',
  '23': 'N/A',
  '1': '3',
  '0': '1',
  '3': '6',
  '2': '3',
  '5': '0',
  '4': '5',
  '7': '0',
  '6': '2',
  '9': '2',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '2',
  '12': 'N/A',
  '15': '4',
  '14': '3',
  '17': '7',
  '16': '2',
  '19': '2',
  '18': '2'},
 'FG3M': {'24': 'N/A',
  '25': 'N/A',
  '20': '1',
  '21': '1',
  '22': '0',
  '23': 'N/A',
  '1': '3',
  '0': '2',
  '3': '2',
  '2': '0',
  '5': '0',
  '4': '0',
  '7': '0',
  '6': '2',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '3',
  '12': 'N/A',
  '15': '0',
  '14': '4',
  '17': '1',
  '16': '2',
  '19': '1',
  '18': '1'},
 'OREB': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '1',
  '23': 'N/A',
  '1': '1',
  '0': '0',
  '3': '0',
  '2': '5',
  '5': '1',
  '4': '1',
  '7': '0',
  '6': '0',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '2',
  '13': '2',
  '12': 'N/A',
  '15': '5',
  '14': '1',
  '17': '0',
  '16': '0',
  '19': '0',
  '18': '2'},
 'FGM': {'24': 'N/A',
  '25': 'N/A',
  '20': '1',
  '21': '1',
  '22': '1',
  '23': 'N/A',
  '1': '3',
  '0': '5',
  '3': '8',
  '2': '10',
  '5': '2',
  '4': '2',
  '7': '1',
  '6': '3',
  '9': '1',
  '8': '0',
  '11': 'N/A',
  '10': '1',
  '13': '6',
  '12': 'N/A',
  '15': '7',
  '14': '8',
  '17': '6',
  '16': '2',
  '19': '3',
  '18': '1'},
 'START_POSITION': {'24': 'N/A',
  '25': 'N/A',
  '20': 'N/A',
  '21': 'N/A',
  '22': 'N/A',
  '23': 'N/A',
  '1': 'F',
  '0': 'F',
  '3': 'G',
  '2': 'C',
  '5': 'N/A',
  '4': 'G',
  '7': 'N/A',
  '6': 'N/A',
  '9': 'N/A',
  '8': 'N/A',
  '11': 'N/A',
  '10': 'N/A',
  '13': 'F',
  '12': 'N/A',
  '15': 'C',
  '14': 'F',
  '17': 'G',
  '16': 'G',
  '19': 'N/A',
  '18': 'N/A'},
 'PF': {'24': 'N/A',
  '25': 'N/A',
  '20': '2',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '6',
  '0': '0',
  '3': '1',
  '2': '4',
  '5': '1',
  '4': '0',
  '7': '2',
  '6': '1',
  '9': '2',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '0',
  '12': 'N/A',
  '15': '1',
  '14': '4',
  '17': '1',
  '16': '1',
  '19': '2',
  '18': '1'},
 'PTS': {'24': 'N/A',
  '25': 'N/A',
  '20': '3',
  '21': '3',
  '22': '2',
  '23': 'N/A',
  '1': '10',
  '0': '15',
  '3': '19',
  '2': '21',
  '5': '4',
  '4': '4',
  '7': '2',
  '6': '9',
  '9': '2',
  '8': '0',
  '11': 'N/A',
  '10': '2',
  '13': '15',
  '12': 'N/A',
  '15': '17',
  '14': '20',
  '17': '17',
  '16': '8',
  '19': '7',
  '18': '3'},
 'FGA': {'24': 'N/A',
  '25': 'N/A',
  '20': '8',
  '21': '2',
  '22': '5',
  '23': 'N/A',
  '1': '10',
  '0': '9',
  '3': '18',
  '2': '16',
  '5': '2',
  '4': '8',
  '7': '3',
  '6': '6',
  '9': '3',
  '8': '0',
  '11': 'N/A',
  '10': '5',
  '13': '12',
  '12': 'N/A',
  '15': '9',
  '14': '17',
  '17': '15',
  '16': '5',
  '19': '5',
  '18': '3'},
 'STL': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '1',
  '0': '2',
  '3': '0',
  '2': '1',
  '5': '0',
  '4': '2',
  '7': '0',
  '6': '0',
  '9': '3',
  '8': '0',
  '11': 'N/A',
  '10': '1',
  '13': '3',
  '12': 'N/A',
  '15': '2',
  '14': '1',
  '17': '2',
  '16': '1',
  '19': '2',
  '18': '0'},
 'FTA': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '1',
  '0': '4',
  '3': '2',
  '2': '2',
  '5': '2',
  '4': '0',
  '7': '0',
  '6': '2',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '0',
  '12': 'N/A',
  '15': '4',
  '14': '2',
  '17': '4',
  '16': '2',
  '19': '0',
  '18': '0'},
 'BLK': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '2',
  '0': '1',
  '3': '0',
  '2': '1',
  '5': '1',
  '4': '0',
  '7': '0',
  '6': '0',
  '9': '1',
  '8': '0',
  '11': 'N/A',
  '10': '1',
  '13': '0',
  '12': 'N/A',
  '15': '0',
  '14': '1',
  '17': '0',
  '16': '2',
  '19': '2',
  '18': '0'},
 'DREB': {'24': 'N/A',
  '25': 'N/A',
  '20': '2',
  '21': '0',
  '22': '5',
  '23': 'N/A',
  '1': '2',
  '0': '4',
  '3': '3',
  '2': '10',
  '5': '2',
  '4': '0',
  '7': '4',
  '6': '2',
  '9': '1',
  '8': '1',
  '11': 'N/A',
  '10': '1',
  '13': '6',
  '12': 'N/A',
  '15': '8',
  '14': '3',
  '17': '0',
  '16': '3',
  '19': '1',
  '18': '3'},
 'FTM': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '1',
  '0': '3',
  '3': '1',
  '2': '1',
  '5': '0',
  '4': '0',
  '7': '0',
  '6': '1',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '0',
  '12': 'N/A',
  '15': '3',
  '14': '0',
  '17': '4',
  '16': '2',
  '19': '0',
  '18': '0'},
 'FT_PCT': {'24': 'N/A',
  '25': 'N/A',
  '20': '0',
  '21': '0',
  '22': '0',
  '23': 'N/A',
  '1': '100',
  '0': '75',
  '3': '50',
  '2': '50',
  '5': '0',
  '4': '0',
  '7': '0',
  '6': '50',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '0',
  '12': 'N/A',
  '15': '75',
  '14': '0',
  '17': '100',
  '16': '100',
  '19': '0',
  '18': '0'},
 'FG_PCT': {'24': 'N/A',
  '25': 'N/A',
  '20': '13',
  '21': '50',
  '22': '20',
  '23': 'N/A',
  '1': '30',
  '0': '56',
  '3': '44',
  '2': '63',
  '5': '100',
  '4': '25',
  '7': '33',
  '6': '50',
  '9': '33',
  '8': '0',
  '11': 'N/A',
  '10': '20',
  '13': '50',
  '12': 'N/A',
  '15': '78',
  '14': '47',
  '17': '40',
  '16': '40',
  '19': '60',
  '18': '33'},
 'FG3_PCT': {'24': 'N/A',
  '25': 'N/A',
  '20': '50',
  '21': '50',
  '22': '0',
  '23': 'N/A',
  '1': '38',
  '0': '50',
  '3': '40',
  '2': '0',
  '5': '0',
  '4': '0',
  '7': '0',
  '6': '67',
  '9': '0',
  '8': '0',
  '11': 'N/A',
  '10': '0',
  '13': '50',
  '12': 'N/A',
  '15': '0',
  '14': '57',
  '17': '25',
  '16': '40',
  '19': '50',
  '18': '100'},
 'SECOND_NAME': {'24': 'Jenkins',
  '25': 'Muscala',
  '20': 'Schroder',
  '21': 'Mack',
  '22': 'Scott',
  '23': 'Brand',
  '1': 'Frye',
  '0': 'Harris',
  '3': 'Oladipo',
  '2': 'Vucevic',
  '5': 'Dedmon',
  '4': 'Payton',
  '7': 'Nicholson',
  '6': 'Green',
  '9': 'Ridnour',
  '8': "O'Quinn",
  '11': 'Gordon',
  '10': 'Harkless',
  '13': 'Carroll',
  '12': 'Marble',
  '15': 'Horford',
  '14': 'Millsap',
  '17': 'Teague',
  '16': 'Korver',
  '19': 'Bazemore',
  '18': 'Antic'},
 'TEAM_CITY': {'24': 'Atlanta',
  '25': 'Atlanta',
  '20': 'Atlanta',
  '21': 'Atlanta',
  '22': 'Atlanta',
  '23': 'Atlanta',
  '1': 'Orlando',
  '0': 'Orlando',
  '3': 'Orlando',
  '2': 'Orlando',
  '5': 'Orlando',
  '4': 'Orlando',
  '7': 'Orlando',
  '6': 'Orlando',
  '9': 'Orlando',
  '8': 'Orlando',
  '11': 'Orlando',
  '10': 'Orlando',
  '13': 'Atlanta',
  '12': 'Orlando',
  '15': 'Atlanta',
  '14': 'Atlanta',
  '17': 'Atlanta',
  '16': 'Atlanta',
  '19': 'Atlanta',
  '18': 'Atlanta'}}

In [24]:
statements = read_file(statements)
headers = read_file(headers)

In [25]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [35]:

## Read outputs from files.
# with open(model_output_file,'r') as f:
#      output = json.load(f)
# extracted_tables = extract_tables_from_responses(output) 
# if reading and extractind directly from gpt model.  
# if model responses are saved and read from a file, helpful for testing and multiple evaluations.
# output_tables_strucbench = generate_output_lines(output_path ='../data/strucbench/table/test.data',end_line= eval_rows) ### gold tables
output_tables_strucbench = generate_output_lines(output_path='../data/table_test_output.txt', end_line=eval_rows)
output_tables_rotowire = generate_output_lines(output_path='../data/rotowire/test.data',end_line = eval_rows)
#print(extracted_tables)

# Now you can process each extracted table

gold_table_player_strucbench = []
gold_table_team_strucbench = []
gold_table_player_rotowire = []
gold_table_team_rotowire = []
model_output_team = []
model_output_player = []

count = 0
# for model_output,gold_label_rotowire,gold_label_strucbench in zip(extracted_tables,output_tables_rotowire,output_tables_strucbench):
for gold_label_rotowire,gold_label_strucbench in zip(output_tables_rotowire,output_tables_strucbench):

    #data_point = tables['data_point']

     gold_tables_rotowire = separate_tables(gold_label_rotowire)
     gold_tables_strucbench = separate_tables(gold_label_strucbench)
     # print(gold_tables_strucbench)
     # print(gold_tables_rotowire)
     if 'Team' not in gold_tables_rotowire or 'Team' not in gold_tables_strucbench or 'Player' not in gold_tables_rotowire or 'Player' not in gold_tables_strucbench:
          count += 1
          continue
     # try: 
     #      model_output_tt = prune_table(model_output['Team'])
     # except:
     #      model_output_tt = ""
     # try:     
     #      model_output_pt = prune_table(model_output['Player'])
     # except:
     #      model_output_pt = ""

     #model_tables = separate_tables(model_output.strip(['Final Answer','\n',':')])
     #print(model_tables)
     # print(model_tables['Player'])
     # print("--------------------------")
     # print(model_tables['Team'])
     #print("---------------------------")
     #print(gold_tables['Player'])
     #print("---------------------------")
     #print(gold_tables['Team'])
     #print("---------------------------")

     # model_output_team.append(model_output_tt)
     # model_output_player.append(model_output_pt) 
     # if 'Player' not in gold_tables_strucbench.keys():
     #      print(gold_label_strucbench)

     gold_table_player_rotowire.append(gold_tables_rotowire['Player'])
     gold_table_team_rotowire.append(gold_tables_rotowire['Team'])
     gold_table_player_strucbench.append(gold_tables_strucbench['Player'])
     gold_table_team_strucbench.append(gold_tables_strucbench['Team'])

In [36]:
print(count)

9

In [37]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [38]:
idx = 0

In [39]:
%clear
import textwrap
print(textwrap.fill(lines[idx],width=100))

The Atlanta Hawks (46 - 12) beat the Orlando Magic (19 - 41) 95 - 88 on Friday. Al Horford had a
good all - around game, putting up 17 points, 13 rebounds, four assists and two steals in a tough
matchup against Nikola Vucevic. Kyle Korver was the lone Atlanta starter not to reach double figures
in points. Jeff Teague bounced back from an illness, he scored 17 points to go along with seven
assists and two steals. After a rough start to the month, the Hawks have won three straight and sit
atop the Eastern Conference with a nine game lead on the second place Toronto Raptors. The Magic
lost in devastating fashion to the Miami Heat in overtime Wednesday. They blew a seven point lead
with 43 seconds remaining and they might have carried that with them into Friday's contest against
the Hawks. Vucevic led the Magic with 21 points and 15 rebounds. Aaron Gordon (ankle) and Evan
Fournier (hip) were unable to play due to injury. The Magic have four teams between them and the
eighth and final playoff spot in the Eastern Conference. The Magic will host the Charlotte Hornets
on Sunday, and the Hawks with take on the Heat in Miami on Saturday.

In [42]:
df = pd.read_json('../data/rotowire_og/test.json')
# print(' '.join(df['summary'][0]))
%clear
print(textwrap.fill(' '.join(df['summary'][idx]), width=100))

The Atlanta Hawks ( 46 - 12 ) beat the Orlando Magic ( 19 - 41 ) 95 - 88 on Friday . Al Horford had
a good all - around game , putting up 17 points , 13 rebounds , four assists and two steals in a
tough matchup against Nikola Vucevic . Kyle Korver was the lone Atlanta starter not to reach double
figures in points . Jeff Teague bounced back from an illness , he scored 17 points to go along with
seven assists and two steals . After a rough start to the month , the Hawks have won three straight
and sit atop the Eastern Conference with a nine game lead on the second place Toronto Raptors . The
Magic lost in devastating fashion to the Miami Heat in overtime Wednesday . They blew a seven point
lead with 43 seconds remaining and they might have carried that with them into Friday 's contest
against the Hawks . Vucevic led the Magic with 21 points and 15 rebounds . Aaron Gordon ( ankle )
and Evan Fournier ( hip ) were unable to play due to injury . The Magic have four teams between them
and the eighth and final playoff spot in the Eastern Conference . The Magic will host the Charlotte
Hornets on Sunday , and the Hawks with take on the Heat in Miami on Saturday .

In [ ]:
input = statements[idx]['response']
header = headers[idx]['response']
lol = dict()
lmao_dict = []
tex = header + input
tex = tex.strip('\n')
lmao =ask_chatgpt(text=tex,prompt_path="prompts/rotowire_gpt4o_make_tables.txt")
lol['response'] = lmao
lmao_dict.append(lol)
pprint.pprint(lmao)
tables = extract_tables_from_responses(lmao_dict)

In [ ]:
convert_to_df(tables[0]['Team'])

In [ ]:
convert_to_df(tables[0]['Player'])

In [19]:
convert_to_df(gold_table_team_rotowire[idx])

          Percentage of field goals Losses Total points Rebounds Wins
0  Knicks                        41     31           82       36    5
1   Bucks                        46     17           95       48   18

In [20]:
convert_to_df(gold_table_player_rotowire[idx])

,,Assists,Defensive rebounds,3-pointers attempted,3-pointers made,Field goals attempted,Field goals made,Free throws attempted,Free throws made,Minutes played,Personal fouls,Points,Total rebounds,Turnovers
0,Giannis Antetokounmpo,,,1,1,9,6,6,3,,,16,12,
1,Zaza Pachulia,,,,,12,6,4,4,,,16,14,
2,Brandon Knight,5,,3,1,14,6,,,,,17,,3
3,Kendall Marshall,,,,,8,6,3,3,,,15,,
4,JR Smith,,,,,,,,,37,2,15,7,2
5,Cole Aldrich,,,,,10,6,,,,,12,7,
6,Tim Hardaway Jr.,4,3,5,3,13,6,4,,,3,17,3,
7,Jason Smith,,,,,11,3,4,4,,,10,,

In [21]:
convert_to_df(gold_table_team_strucbench[idx])

          Percentage of field goals Losses Total points Rebounds Wins
0  Knicks                        41     31           82       36    5
1   Bucks                        46     17           95       48   18

In [22]:
convert_to_df(gold_table_player_strucbench[idx])

,,Assists,Defensive rebounds,3-pointers attempted,3-pointers made,Field goals attempted,Field goals made,Free throws attempted,Free throws made,Minutes played,Personal fouls,Points,Total rebounds,Turnovers
0,Giannis Antetokounmpo,,,1,1,9,6,6,3,,,16,12,
1,Zaza Pachulia,,,,,12,6,4,4,,,16,14,
2,Brandon Knight,5,3,3,1,14,6,,,,3,17,,3
3,Kendall Marshall,,,,,8,6,3,3,20,,15,,
4,JR Smith,,,,,,,,,,,15,7,
5,Cole Aldrich,,,,,10,6,,,19,,12,7,
6,Tim Hardaway Jr.,4,,5,3,13,6,,,,,17,,

In [9]:
unequal_str_player_idx = []
unequal_str_team_idx = []
for i in range(700):
    # print(i)
    if gold_table_player_rotowire[i] != gold_table_player_strucbench[i]:
        unequal_str_player_idx.append(i)
    if gold_table_team_rotowire[i] != gold_table_team_strucbench[i]:
        unequal_str_team_idx.append(i)

# if gold_table_player_rotowire[idx] == gold_table_player_strucbench[idx]:
    # print('equal text')

In [10]:
print(unequal_str_player_idx)
print(len(unequal_str_player_idx))

[1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 22, 23, 24, 27, 28, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 86, 87, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 122, 123, 125, 126, 127, 128, 129, 130, 132, 133, 134, 135, 136, 137, 138, 139, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 154, 155, 156, 157, 158, 159, 160, 161, 162, 164, 165, 166, 167, 168, 173, 174, 175, 176, 177, 179, 180, 181, 182, 183, 184, 185, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 210, 211, 212, 213, 216, 217, 218, 219, 220, 221, 222, 223, 226, 227, 228, 229, 230, 231, 232, 233, 234, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 259, 260, 261, 262, 263, 264, 266, 268, 271, 272, 273, 274, 275, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 289, 290, 291, 292, 293, 294, 295, 296, 297, 300, 301, 303, 304, 305, 307, 308, 309, 310, 311, 312, 314, 315, 316, 317, 318, 319, 320, 321, 323, 324, 325, 326, 327, 329, 330, 332, 335, 336, 338, 339, 340, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 360, 362, 364, 365, 366, 367, 368, 369, 370, 371, 372, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 388, 390, 392, 393, 394, 397, 398, 399, 400, 401, 402, 403, 404, 405, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423, 424, 425, 429, 430, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 445, 446, 447, 448, 449, 450, 453, 454, 455, 456, 457, 459, 460, 461, 462, 464, 465, 466, 467, 468, 470, 471, 472, 473, 474, 475, 476, 478, 479, 482, 483, 484, 485, 487, 488, 489, 490, 491, 492, 493, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 555, 556, 558, 559, 560, 561, 562, 563, 566, 567, 568, 569, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 590, 591, 592, 593, 595, 597, 598, 599, 600, 602, 603, 605, 607, 608, 611, 612, 614, 616, 618, 620, 621, 622, 623, 624, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 639, 640, 641, 643, 646, 647, 648, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 661, 662, 663, 664, 666, 667, 668, 669, 670, 671, 672, 673, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699]
578

In [11]:
print(unequal_str_team_idx)
print(len(unequal_str_team_idx))

[3, 4, 6, 8, 9, 10, 11, 14, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 32, 34, 35, 37, 38, 39, 40, 44, 49, 50, 53, 55, 56, 58, 60, 61, 62, 63, 64, 66, 67, 68, 74, 75, 76, 78, 81, 82, 83, 90, 92, 95, 96, 97, 98, 100, 103, 104, 107, 109, 110, 111, 112, 113, 114, 115, 118, 121, 122, 123, 124, 128, 131, 133, 134, 135, 137, 138, 139, 140, 142, 145, 146, 148, 149, 150, 153, 156, 157, 158, 160, 163, 164, 165, 168, 169, 170, 176, 177, 178, 180, 181, 182, 188, 189, 190, 194, 195, 197, 199, 200, 201, 202, 204, 208, 209, 211, 212, 213, 216, 217, 218, 219, 225, 226, 227, 228, 230, 231, 233, 234, 238, 247, 249, 250, 253, 255, 257, 259, 261, 262, 264, 265, 267, 272, 273, 277, 281, 282, 286, 287, 288, 291, 292, 297, 298, 299, 301, 306, 309, 310, 312, 317, 318, 322, 323, 324, 325, 326, 327, 328, 330, 333, 334, 337, 341, 342, 343, 345, 348, 349, 350, 354, 357, 359, 361, 364, 365, 369, 370, 374, 375, 376, 377, 380, 381, 382, 384, 387, 388, 391, 393, 394, 395, 396, 397, 398, 409, 412, 413, 414, 416, 418, 420, 421, 423, 424, 425, 427, 428, 429, 431, 433, 434, 438, 440, 442, 443, 444, 445, 446, 450, 455, 459, 461, 462, 464, 466, 467, 469, 471, 472, 473, 475, 480, 483, 484, 485, 487, 489, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 548, 549, 550, 551, 552, 554, 555, 556, 557, 559, 561, 562, 565, 566, 569, 572, 575, 576, 577, 578, 580, 583, 584, 586, 588, 589, 590, 591, 592, 593, 594, 595, 596, 603, 605, 606, 607, 608, 609, 611, 612, 614, 616, 619, 620, 621, 623, 625, 632, 633, 634, 636, 639, 646, 647, 649, 652, 653, 655, 656, 658, 659, 668, 670, 671, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699]
394

In [ ]:
te = """ The Cleveland Cavaliers completed their sweep of the Boston Celtics with a 101-93 win on Sunday.
The Cleveland Cavaliers entered the game with a 3-0 lead in the series.
The Cleveland Cavaliers won both of the first two quarters to take a 57-36 lead at halftime.
Coach David Blatt chose to play his key players for most of the game to ensure a win.
LeBron James played 46 minutes in the game.
Kyrie Irving played 43 minutes in the game.
Kevin Love was forced from the game in the first quarter with a dislocated left shoulder.
Kelly Olynyk pulled down on Kevin Love's arm while fighting for a rebound, causing Love's injury.
Kendrick Perkins put a hard screen on Jae Crowder in the second quarter.
Kendrick Perkins was assessed a technical foul and a flagrant-1 foul for his actions.
Jae Crowder was assessed a technical foul for his response to Kendrick Perkins' screen.
J.R. Smith hit Jae Crowder in the face with a backhand in the third quarter.
J.R. Smith was given a flagrant-2 foul and automatically ejected from the game.
Jae Crowder injured his knee during the J.R. Smith incident and left the game.
Jae Crowder suffered a left knee sprain and was unable to return to the game.
The Boston Celtics outscored the Cleveland Cavaliers 25-13 in the third quarter.
The Cleveland Cavaliers carried a nine-point lead into the fourth quarter.
The Cleveland Cavaliers never let the Boston Celtics get closer than a six-point divide in the fourth quarter.
The Cleveland Cavaliers will advance to the Eastern Conference semifinals.
The Cleveland Cavaliers will play the winner of the Bulls/Bucks series in the Eastern Conference semifinals.
Kevin Love's status will be updated after he undergoes tests with the team's doctors.
J.R. Smith and Kendrick Perkins appear in line for suspensions for their actions in the game. 
Table Headers:
{
    "Team" : {
        "row_headers" : ["Cleveland Cavaliers", "Boston Celtics"],
        "column_headers" : ["Final Score", "Series Lead", "Half Time Score", "Third Quarter Score", "Fourth Quarter Score", "Advancement", "Next Opponent"]
    },
    "Player" : {
        "row_headers" : ["LeBron James", "Kyrie Irving", "Kevin Love", "Kelly Olynyk", "Kendrick Perkins", "Jae Crowder", "J.R. Smith"],
        "col_headers" : ["Minutes Played", "Injury Status", "Fouls", "Ejection Status", "Suspension Status"]
    }
}
"""

In [ ]:
pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

In [ ]:
pprint.pprint(ask_gemini(
    prompt_path="prompts/rotowire_prompt_verify.txt",
    text= te.strip('\n')
))

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
pprint.pprint(output[idx]['input'])

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
df = convert_to_df(model_output_player[idx])
from tabulate import tabulate
print(tabulate(df, headers='keys', tablefmt='pretty'))
print(df)

In [ ]:
convert_to_df(gold_table_player[idx])

In [ ]:
convert_to_df(model_output_team[idx])

In [ ]:
convert_to_df(gold_table_team[idx])

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_player[i],gold_table_player[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_player[i],gold_table_player[i]))

## Team Table Compare

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_team[i],gold_table_team[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_team[i],gold_table_team[i]))