## Notebook for Manual Analysis of Generated Tables

In [1]:
import pandas as pd
import numpy as np
import json
from utils.utils import *
import pprint
from eval.eval import *
from post_processing.post_processing import *
from utils.table_utils import *
from model_inference.gpt import *
from model_inference.llama import *
from model_inference.gemini import *
eval_rows = 50
model_output_file = "model_outputs/llama_baseline_2610_117AM/tables_gpt_trial.json"
statements ="model_outputs/llama_baseline_2610_117AM/ai_response.json"
headers = "model_outputs/llama_baseline_2610_117AM/headers.json"
gold_table_file = "data/rotowire/test.text"

In [2]:
statements = read_file(statements)
headers = read_file(headers)

In [3]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [4]:

## Read outputs from files.
with open(model_output_file,'r') as f:
     output = json.load(f)
extracted_tables = extract_tables_from_responses(output) 
# if reading and extractind directly from gpt model.  
# if model responses are saved and read from a file, helpful for testing and multiple evaluations.
output_tables_rotowire = generate_output_lines(output_path ='data/rotowire/test.data',end_line= eval_rows) ### gold tables
output_tables_strucbench = generate_output_lines(output_path ='data/Strucbench/test.data',end_line= eval_rows) ### gold tables
#print(extracted_tables)

# Now you can process each extracted table

gold_table_player_rotowire = []
gold_table_team_rotowire = []
gold_table_player_strucbench = []
gold_table_team_strucbench = []
model_output_team = []
model_output_player = []
for model_output,gold_label_rotowire, gold_label_strucbench in zip(extracted_tables,output_tables_rotowire,output_tables_strucbench):
    #data_point = tables['data_point']

     gold_tables_rotowire = separate_tables(gold_label_rotowire)
     gold_tables_strucbench = separate_tables(gold_label_strucbench)
     try: 
          model_output_tt = prune_table(model_output['Team'])
     except:
          model_output_tt = ""
     try:     
          model_output_pt = prune_table(model_output['Player'])
     except:
          model_output_pt = ""

     #model_tables = separate_tables(model_output.strip(['Final Answer','\n',':')])
     #print(model_tables)
     # print(model_tables['Player'])
     # print("--------------------------")
     # print(model_tables['Team'])
     #print("---------------------------")
     #print(gold_tables['Player'])
     #print("---------------------------")
     #print(gold_tables['Team'])
     #print("---------------------------")

     model_output_team.append(model_output_tt)
     model_output_player.append(model_output_pt) 
     gold_table_player_rotowire.append( gold_tables_rotowire['Player'])
     gold_table_team_rotowire.append(gold_tables_rotowire['Team'])
     gold_table_player_strucbench.append( gold_tables_strucbench['Player'])
     gold_table_team_strucbench.append(gold_tables_strucbench['Team'])

Table 'Team' found for data_point 0
Table 'Player' found for data_point 0
Table 'Upcoming Games' found for data_point 0
Table 'Standings' found for data_point 0
Table 'Team' found for data_point 1
Table 'Player' found for data_point 1
Table 'Upcoming Games' found for data_point 1
Table 'Team' found for data_point 2
Table 'Player' found for data_point 2
Table 'Upcoming Games' found for data_point 2
Table 'Team' found for data_point 3
Table 'Player' found for data_point 3
Table 'Upcoming Games' found for data_point 3
Table 'Team' found for data_point 4
Table 'Player' found for data_point 4
Table 'Upcoming Games' found for data_point 4
Table 'Conference Standing' found for data_point 4
Table 'Team' found for data_point 5
Table 'Player' found for data_point 5
Table 'Upcoming Games' found for data_point 5
Table 'Team' found for data_point 6
Table 'Player' found for data_point 6
Table 'Game Series' found for data_point 6
Table 'Player Status' found for data_point 6
Table 'Team' found for data_point 7
Table 'Player' found for data_point 7
Table 'Upcoming Games' found for data_point 7
Table 'Player' found for data_point 8
Table 'Team' found for data_point 9
Table 'Player' found for data_point 9
Table 'Team' found for data_point 10
Table 'Conference Position' found for data_point 10
Table 'Player' found for data_point 10
Table 'Team' found for data_point 11
Table 'Player' found for data_point 11
Table 'Team' found for data_point 12
Table 'Player' found for data_point 12
Table 'Bench Unit' found for data_point 12
Table 'Team' found for data_point 13
Table 'Player' found for data_point 13
Table 'Upcoming Games' found for data_point 13
Table 'Standings' found for data_point 13
Table 'Team' found for data_point 14
Table 'Player' found for data_point 14
Table 'Upcoming Games' found for data_point 14
Table 'Game Results' found for data_point 15
Table 'Player Statistics' found for data_point 15
Table 'Upcoming Games' found for data_point 15
Table 'Team' found for data_point 16
Table 'Player' found for data_point 16
Table 'Points Score' found for data_point 16
Table 'Team' found for data_point 17
Table 'Player' found for data_point 17
Table 'Team Overview' found for data_point 18
Table 'Player Stats' found for data_point 18
Table 'Upcoming Games' found for data_point 18
Table 'Player' found for data_point 19
Table 'Other Information' found for data_point 19
Table 'Player' found for data_point 20
Table 'Team' found for data_point 20
Table 'Team' found for data_point 21
Table 'Player' found for data_point 21
Table 'Upcoming Games' found for data_point 21
Table 'Division Standings' found for data_point 21
Table 'Player' found for data_point 22
Table 'Team' found for data_point 22
Table 'Team' found for data_point 23
Table 'Player' found for data_point 23
Table 'Upcoming Games' found for data_point 23
Table 'Team' found for data_point 24
Table 'Team' found for data_point 25
Table 'Player' found for data_point 25
Table 'Team Records' found for data_point 25
Table 'Team' found for data_point 26
Table 'Player' found for data_point 26
Table 'Upcoming Games' found for data_point 26
Table 'Team' found for data_point 27
Table 'Player' found for data_point 27
Table 'Upcoming Games' found for data_point 27
Table 'Team' found for data_point 28
Table 'Player' found for data_point 28
Table 'Upcoming Games' found for data_point 28
Table 'Not Played' found for data_point 28
Table 'Team' found for data_point 29
Table 'Player' found for data_point 29
Table 'Team' found for data_point 30
Table 'Player' found for data_point 30
Table 'Team' found for data_point 31
Table 'Player' found for data_point 31
Table 'Upcoming Games' found for data_point 31
Table 'Goals' found for data_point 31
Table 'Team' found for data_point 32
Table 'Player' found for data_point 32
Table 'Upcoming Games' found for data_point 32
Table 'Team' found for data_point 33
Table 'Player' found for data_point 33
Table 'Upcoming Games' found for data_point 33
Table 'Team' found for data_point 34
Table 'Player' found for data_point 34
Table 'Upcoming Games' found for data_point 34
Table 'Rested Players' found for data_point 34
Table 'Team' found for data_point 35
Table 'Player' found for data_point 35
Table 'Upcoming Games' found for data_point 35
Table 'Team' found for data_point 36
Table 'Player' found for data_point 36
Table 'Upcoming Games' found for data_point 36
Table 'Team' found for data_point 37
Table 'Player' found for data_point 37
Table 'Team Game Statistics' found for data_point 38
Table 'Individual Player Statistics' found for data_point 38
Table 'Upcoming Games' found for data_point 38
Table 'Player' found for data_point 39
Table 'Team' found for data_point 40
Table 'Player' found for data_point 40
Table 'Miscellaneous Information' found for data_point 40
Table 'Team' found for data_point 41
Table 'Player' found for data_point 41
Table 'Upcoming Games' found for data_point 41
Table 'Team' found for data_point 42
Table 'Player' found for data_point 42
Table 'Team' found for data_point 43
Table 'Player' found for data_point 43
Table 'Team' found for data_point 44
Table 'Player' found for data_point 44
Table 'Upcoming Games' found for data_point 44
Table 'Team' found for data_point 45
Table 'Player' found for data_point 45
Table 'Team' found for data_point 46
Table 'Player' found for data_point 46
Table 'Team' found for data_point 47
Table 'Player' found for data_point 47
Table 'Team' found for data_point 48
Table 'Player' found for data_point 48
Table 'Team' found for data_point 49
Table 'Player' found for data_point 49

In [5]:
### Reading Gold Labels
gold_texts = []
with open(gold_table_file,"r") as f:
    lines = [line.strip() for line in f.readlines()]

In [6]:
idx = 6

In [7]:
%clear
import textwrap
print(textwrap.fill(lines[idx],width=100))

The second - seed Cleveland Cavaliers (40) completed their sweep of the seventh - seed Boston
Celtics (0 - 4) in a 101 - 93 slugfest Sunday. Cleveland came out with purpose in the first half,
wining both of the first two quarters to go into the break with 57 - 36 lead. Coach David Blatt
could have taken the game easy with the Cavs up 30 in the series, but he opted to push the
accelerator to the floor and used his big guns for most of the game to ensure a win and an end to
the Cavs' first - round series. LeBron James played a team - high 46 minutes and was followed
closely by Kyrie Irving with 43 minutes of his own. Kevin Love was forced from the game in the first
quarter with what appeared to be a dislocated left shoulder after Celtics big man Kelly Olynyk
appeared to pull down on Love's arm while fighting for a rebound. Love was n't the only player to be
forced from the game, and the Love/Olynyk incident was n't the only physical altercation. In the
second quarter, Kendrick Perkins put a hard screen on Jae Crowder, pushing Crowder in his face and
forcing him to the ground before antagonizing Crowder with a tap to the face with a closed fist.
Both Perkins and Crowder were assessed technical fouls, and Perkins earned a flagrant - 1 foul for
the tap to Crowder's face. Shortly after halftime, Crowder was hit in the face by a backhand from
J.R. Smith. Smith was given a flagrant - 2 and automatically ejected from the game as a result.
Crowder injured his knee during the Smith incident and left the game with a left knee sprain, unable
to return. The Celtics made a run in the third quarter, outscoring the Cavs 25 - 13 in the third
window, but it was n't enough. Cleveland carried a nine - point lead into the fourth quarter and
never let Boston get closer than a six - point divide at 99 - 93 with under a minute left in the
game. The Cavaliers will advance to the Eastern Conference semifinals, and they'll play the winner
of the Bulls/Bucks series that is currently at 3 - 1 with the Bulls holding the advantage. Kevin
Love's status will be updated after he gets back to Cleveland and undergoes tests with the team's
doctors. Smith and Perkins appear in line for suspensions, and a judgment on their statuses will
likely be handed down before the start of the conference semifinals.

In [8]:
input = statements[idx]['response']
header = headers[idx]['response']
lol = dict()
lmao_dict = []
tex = header + input
tex = tex.strip('\n')
lmao =ask_chatgpt(text=tex,prompt_path="prompts/rotowire_gpt4o_make_tables.txt")
lol['response'] = lmao
lmao_dict.append(lol)
pprint.pprint(lmao)
tables = extract_tables_from_responses(lmao_dict)

jere

APIConnectionError: Connection error.

In [46]:
convert_to_df(tables[0]['Team'])

,Final Score,Series Lead,Half Time Score,Third Quarter Score,Fourth Quarter Score,Advancement,Next Opponent,
0,Cleveland Cavaliers,101,3-0,57-36,13,,Advance to Eastern Conference semifinals,Winner of Bulls/Bucks series
1,Boston Celtics,93,,,25,,,

In [47]:
convert_to_df(tables[0]['Player'])

,Minutes Played,Injury Status,Fouls,Ejection Status,Suspension Status,
0,LeBron James,46,,,,
1,Kyrie Irving,43,,,,
2,Kevin Love,,Dislocated left shoulder,,,
3,Kelly Olynyk,,,,,
4,Kendrick Perkins,,,"Technical foul, Flagrant-1",,Appears in line for suspension
5,Jae Crowder,,Left knee sprain,Technical foul,Ejected,Appears in line for suspension
6,J.R. Smith,,,Flagrant-2,Ejected,Appears in line for suspension

In [48]:
convert_to_df(gold_table_team_rotowire[idx])

,,Percentage of field goals,Losses,Total points,Points in 3rd quarter,Wins
0,Celtics,,4,93,25,0
1,Cavaliers,40,,101,13,

In [49]:
convert_to_df(gold_table_player_rotowire[idx])

,,3-pointers made,Minutes played,Personal fouls,Total rebounds,Steals
0,LeBron James,,46,,,
1,Kevin Love,,,,1,
2,JR Smith,2,,,,2
3,Kyrie Irving,,43,,,
4,Kendrick Perkins,,,1,,
5,Kelly Olynyk,,,,1,

In [ ]:
convert_to_df(gold_table_team_strucbench[idx])

In [ ]:
convert_to_df(gold_table_player_strucbench[idx])

In [29]:
te = """ The Cleveland Cavaliers completed their sweep of the Boston Celtics with a 101-93 win on Sunday.
The Cleveland Cavaliers entered the game with a 3-0 lead in the series.
The Cleveland Cavaliers won both of the first two quarters to take a 57-36 lead at halftime.
Coach David Blatt chose to play his key players for most of the game to ensure a win.
LeBron James played 46 minutes in the game.
Kyrie Irving played 43 minutes in the game.
Kevin Love was forced from the game in the first quarter with a dislocated left shoulder.
Kelly Olynyk pulled down on Kevin Love's arm while fighting for a rebound, causing Love's injury.
Kendrick Perkins put a hard screen on Jae Crowder in the second quarter.
Kendrick Perkins was assessed a technical foul and a flagrant-1 foul for his actions.
Jae Crowder was assessed a technical foul for his response to Kendrick Perkins' screen.
J.R. Smith hit Jae Crowder in the face with a backhand in the third quarter.
J.R. Smith was given a flagrant-2 foul and automatically ejected from the game.
Jae Crowder injured his knee during the J.R. Smith incident and left the game.
Jae Crowder suffered a left knee sprain and was unable to return to the game.
The Boston Celtics outscored the Cleveland Cavaliers 25-13 in the third quarter.
The Cleveland Cavaliers carried a nine-point lead into the fourth quarter.
The Cleveland Cavaliers never let the Boston Celtics get closer than a six-point divide in the fourth quarter.
The Cleveland Cavaliers will advance to the Eastern Conference semifinals.
The Cleveland Cavaliers will play the winner of the Bulls/Bucks series in the Eastern Conference semifinals.
Kevin Love's status will be updated after he undergoes tests with the team's doctors.
J.R. Smith and Kendrick Perkins appear in line for suspensions for their actions in the game. 
Table Headers:
{
    "Team" : {
        "row_headers" : ["Cleveland Cavaliers", "Boston Celtics"],
        "column_headers" : ["Final Score", "Series Lead", "Half Time Score", "Third Quarter Score", "Fourth Quarter Score", "Advancement", "Next Opponent"]
    },
    "Player" : {
        "row_headers" : ["LeBron James", "Kyrie Irving", "Kevin Love", "Kelly Olynyk", "Kendrick Perkins", "Jae Crowder", "J.R. Smith"],
        "col_headers" : ["Minutes Played", "Injury Status", "Fouls", "Ejection Status", "Suspension Status"]
    }
}
"""

In [16]:
pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
/var/folders/13/lbgl_ydd4jlcd4ht05rj1t9r0000gn/T/ipykernel_2108/72300718.py:1: SyntaxWarning: invalid escape sequence '\ '
  pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))
/var/folders/13/lbgl_ydd4jlcd4ht05rj1t9r0000gn/T/ipykernel_2108/72300718.py:1: SyntaxWarning: invalid escape sequence '\ '
  pprint.pprint(ask_chatgpt(text=(input+header)('\n').strip('\ '),prompt_path="prompts/rotowire_gpt4o_make_tables.txt"))

TypeError: 'str' object is not callable

In [ ]:
pprint.pprint(ask_gemini(
    prompt_path="prompts/rotowire_prompt_verify.txt",
    text= te.strip('\n')
))

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
pprint.pprint(output[idx]['input'])

In [ ]:
pprint.pprint(output[idx]['response'])

In [ ]:
df = convert_to_df(model_output_player[idx])
from tabulate import tabulate
print(tabulate(df, headers='keys', tablefmt='pretty'))
print(df)

In [ ]:
convert_to_df(gold_table_player[idx])

In [ ]:
convert_to_df(model_output_team[idx])

In [ ]:
convert_to_df(gold_table_team[idx])

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_player[i],gold_table_player[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_player[i],gold_table_player[i]))

## Team Table Compare

In [ ]:
for i in range(0,50):
    print(i,custom_compare_tables(model_output_team[i],gold_table_team[i]))

In [ ]:
for i in range(0,50):
    print(i,compare_values(model_output_team[i],gold_table_team[i]))